In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import GridSearchCV, StratifiedShuffleSplit
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from scipy.special import entr
from sklearn import preprocessing
import matplotlib.pyplot as plt
import math
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from IPython.display import display
#import itertools
#from itables import init_notebook_mode
import random
#init_notebook_mode(all_interactive=True)

In [9]:
def modify_timestamps(dfs):
    modified_dfs = []
    for df in dfs:
        if not df.empty:
            df['timestamp_modified'] = df['timestamp'].iloc[0] + df.index * 10
        modified_dfs.append(df)
    return modified_dfs

In [37]:
# Using pickle, load modification_timestamp.pkl file
# Path: timestamp_modify_to_make_it_one.ipynb
import pickle
with open('modification_timestamp.pkl', 'rb') as f:
    ttt = pickle.load(f)

In [42]:
del ttt

In [3]:
import pickle
# Load the dictionary back from the pickle file.
with open('user_dict_modified_timestamp.pkl', 'rb') as f:
    user_dict = pickle.load(f)

In [43]:
del user_dict['18']

In [46]:
# Create temporary dictionary to store modified dataframes
temp_dict = {}
# For loop that calls mofify_timestamp function on each list of user's dataframe
for user in user_dict:
    temp_dict[user] = modify_timestamps(user_dict[user])

# Check first five rows for each user
for user in temp_dict:
    print(user)
    print(temp_dict[user][0].head())
    print()

1
     client_timestamp    x    y button state    window\n      timestamp  \
0      1570169899.971  694  489   None  Move  browsing\n  1570169899971
1       1570169899.99  703  473   None  Move  browsing\n  1570169899990
2  1570169900.0089998  713  454   None  Move  browsing\n  1570169900008
3      1570169900.028  725  436   None  Move  browsing\n  1570169900028
4      1570169900.046  737  417   None  Move  browsing\n  1570169900046

   timestamp_modified
0       1570169899971
1       1570169899981
2       1570169899991
3       1570169900001
4       1570169900011

10
     client_timestamp     x    y button state    window\n      timestamp  \
0  1570172649.4120002   960  542   None  Move  browsing\n  1570172649412
1       1570172649.42   984  636   None  Move  browsing\n  1570172649420
2      1570172649.436   994  719   None  Move  browsing\n  1570172649436
3      1570172649.444   997  748   None  Move  browsing\n  1570172649444
4      1570172649.452  1001  773   None  Move  browsing\n  1570172649452

   timestamp_modified
0       1570172649412
1       1570172649422
2       1570172649432
3       1570172649442
4       1570172649452

11
     client_timestamp    x    y button state    window\n      timestamp  \
0      1568522337.605  704   98   None  Move  browsing\n  1568522337605
1  1568522337.6139998  708  121   None  Move  browsing\n  1568522337613
2       1568522337.62  713  183   None  Move  browsing\n  1568522337620
3      1568522337.627  716  233   None  Move  browsing\n  1568522337627
4  1568522337.6339998  719  303   None  Move  browsing\n  1568522337633

   timestamp_modified
0       1568522337605
1       1568522337615
2       1568522337625
3       1568522337635
4       1568522337645

12
     client_timestamp     x   y button     state    window\n      timestamp  \
2949   1573197345.684  1797  17   Left  Released  browsing\n  1573197345684
2950    1573197346.15  1797  17   None      Move  browsing\n  1573197346150
2951   1573197346.171  1788  21   None      Move  browsing\n  1573197346171
2952   1573197346.188  1743  48   None      Move  browsing\n  1573197346188
2953   1573197346.206  1668  79   None      Move  browsing\n  1573197346206

      timestamp_modified
2949       1573197375174
2950       1573197375184
2951       1573197375194
2952       1573197375204
2953       1573197375214

13
    client_timestamp     x    y button     state    window\n      timestamp  \
301   1570602866.831  2612  400   Left  Released  browsing\n  1570602866831
302   1570602866.843  2612  400   None      Move  browsing\n  1570602866843
303   1570602866.863  2612  399   None      Move  browsing\n  1570602866863
304   1570602867.035  2612  398   None      Move  browsing\n  1570602867035
305   1570602867.046  2607  396   None      Move  browsing\n  1570602867046

     timestamp_modified
301       1570602869841
302       1570602869851
303       1570602869861
304       1570602869871
305       1570602869881

14
     client_timestamp    x    y button state    window\n      timestamp  \
0      1574657265.646  960  541   None  Move  browsing\n  1574657265646
1  1574657265.6520002  929  562   None  Move  browsing\n  1574657265652
2      1574657265.666  843  575   None  Move  browsing\n  1574657265666
3      1574657265.675  795  578   None  Move  browsing\n  1574657265675
4  1574657265.6820002  734  578   None  Move  browsing\n  1574657265682

   timestamp_modified
0       1574657265646
1       1574657265656
2       1574657265666
3       1574657265676
4       1574657265686

15
     client_timestamp    x     y button state    window\n      timestamp  \
0      1578464301.704  886   560   None  Move  browsing\n  1578464301704
1  1578464301.7329998  642  1173   None  Move  browsing\n  1578464301732
2      1578464301.745  573  1460   None  Move  browsing\n  1578464301745
3      1578464301.843  138  3365   None  Move  browsing\n  1578464301843
4      1578464301.871  106  1841   None  Move  browsing\n  1578464301871

   timestamp_modified
0       1578464301704
1       1578464301714
2       1578464301724
3       1578464301734
4       1578464301744

16
      client_timestamp     x     y button state    window\n      timestamp  \
21      1569394025.776  1660   719   None  Move  browsing\n  1569394025776
22  1569394025.7970002  1341   719   None  Move  browsing\n  1569394025797
23      1569394025.803  1370   730   None  Move  browsing\n  1569394025803
24  1569394025.8179998  1353   790   None  Move  browsing\n  1569394025817
25      1569394025.819  1388  1046   None  Move  browsing\n  1569394025819

    timestamp_modified
21       1569394025986
22       1569394025996
23       1569394026006
24       1569394026016
25       1569394026026

17
       client_timestamp     x    y button state    window\n      timestamp  \
143  1571900881.6360002  1213  377   None  Move  browsing\n  1571900881636
144      1571900881.644  1203  409   None  Move  browsing\n  1571900881644
145  1571900881.6520002  1193  441   None  Move  browsing\n  1571900881652
146       1571900881.66  1187  473   None  Move  browsing\n  1571900881660
147      1571900881.667  1181  507   None  Move  browsing\n  1571900881667

     timestamp_modified
143       1571900883066
144       1571900883076
145       1571900883086
146       1571900883096
147       1571900883106

19
  client_timestamp     x    y button state    window\n      timestamp  \
3    1574317057.93  1008  400   None  Move  browsing\n  1574317057930
4   1574317057.946  1008  399   None  Move  browsing\n  1574317057946
5   1574317057.954  1004  393   None  Move  browsing\n  1574317057954
6   1574317057.962  1001  390   None  Move  browsing\n  1574317057962
7    1574317057.97   979  374   None  Move  browsing\n  1574317057970

   timestamp_modified
3       1574317057960
4       1574317057970
5       1574317057980
6       1574317057990
7       1574317058000

2
         client_timestamp    x     y button state    window\n      timestamp  \
10039      1563786727.844  267  1002   None  Move  browsing\n  1563786727844
10040      1563786727.855  392   956   None  Move  browsing\n  1563786727855
10041  1563786727.8660002  440   930   None  Move  browsing\n  1563786727866
10042       1563786727.87  499   898   None  Move  browsing\n  1563786727870
10043      1563786727.875  561   865   None  Move  browsing\n  1563786727875

       timestamp_modified
10039       1563786828234
10040       1563786828244
10041       1563786828254
10042       1563786828264
10043       1563786828274

3
   client_timestamp    x     y button state    window\n      timestamp  \
71   1571378717.301  565  1079   None  Move  browsing\n  1571378717301
72   1571378717.316  564  1079   None  Move  browsing\n  1571378717316
73   1571378717.332  563  1079   None  Move  browsing\n  1571378717332
74   1571378717.347  562  1079   None  Move  browsing\n  1571378717347
75   1571378717.363  561  1079   None  Move  browsing\n  1571378717363

    timestamp_modified
71       1571378718011
72       1571378718021
73       1571378718031
74       1571378718041
75       1571378718051

4
       client_timestamp    x    y button state    window\n      timestamp  \
208  1572592265.5170002  208  742   None  Move  browsing\n  1572592265517
209      1572592265.525  211  736   None  Move  browsing\n  1572592265525
210      1572592265.533  213  733   None  Move  browsing\n  1572592265533
211  1572592265.5570002  222  715   None  Move  browsing\n  1572592265557
212      1572592265.589  248  680   None  Move  browsing\n  1572592265589

     timestamp_modified
208       1572592267597
209       1572592267607
210       1572592267617
211       1572592267627
212       1572592267637

5
     client_timestamp     x    y button state    window\n      timestamp  \
2761   1571447188.294  1136  588   None  Move  browsing\n  1571447188294
2762   1571447188.326  1125  595   None  Move  browsing\n  1571447188326
2763    1571447188.34  1120  598   None  Move  browsing\n  1571447188340
2764   1571447188.356  1117  599   None  Move  browsing\n  1571447188356
2765   1571447188.435  1116  599   None  Move  browsing\n  1571447188435

      timestamp_modified
2761       1571447215904
2762       1571447215914
2763       1571447215924
2764       1571447215934
2765       1571447215944

6
     client_timestamp    x    y button state    window\n      timestamp  \
0       1571503113.11  233  273   None  Move  browsing\n  1571503113110
1  1571503113.1220002  233  276   None  Move  browsing\n  1571503113122
2       1571503113.13  233  280   None  Move  browsing\n  1571503113130
3  1571503113.1420002  233  282   None  Move  browsing\n  1571503113142
4       1571503113.15  233  285   None  Move  browsing\n  1571503113150

   timestamp_modified
0       1571503113110
1       1571503113120
2       1571503113130
3       1571503113140
4       1571503113150

7
     client_timestamp     x     y button state    window\n      timestamp  \
0        1568537725.6  1734  1010   None  Move  browsing\n  1568537725600
1      1568537725.606  1737  1005   None  Move  browsing\n  1568537725606
2  1568537725.6139998  1740  1001   None  Move  browsing\n  1568537725613
3  1568537725.6220002  1742   994   None  Move  browsing\n  1568537725622
4      1568537725.629  1744   988   None  Move  browsing\n  1568537725629

   timestamp_modified
0       1568537725600
1       1568537725610
2       1568537725620
3       1568537725630
4       1568537725640

8
       client_timestamp     x    y button state    window\n      timestamp  \
506      1568614213.045  1473  470   None  Move  browsing\n  1568614213045
507      1568614213.053  1475  460   None  Move  browsing\n  1568614213053
508      1568614213.059  1475  460   None  Move  browsing\n  1568614213059
509  1568614213.0670002  1475  460   None  Move  browsing\n  1568614213067
510      1568614213.079  1475  462   None  Move  browsing\n  1568614213079

     timestamp_modified
506       1568614218105
507       1568614218115
508       1568614218125
509       1568614218135
510       1568614218145

9
  client_timestamp     x    y button state    window\n      timestamp  \
0   1571560982.716  1463  281   None  Move  browsing\n  1571560982716
1   1571560982.732  1849   48   None  Move  browsing\n  1571560982732
2    1571560982.74  2010  -50   None  Move  browsing\n  1571560982740
3   1571560982.748  2067  -92   None  Move  browsing\n  1571560982748
4   1571560982.756  2037  -90   None  Move  browsing\n  1571560982756

   timestamp_modified
0       1571560982716
1       1571560982726
2       1571560982736
3       1571560982746
4       1571560982756

In [47]:
temp_dict.keys()

dict_keys(['1', '10', '11', '12', '13', '14', '15', '16', '17', '19', '2', '3', '4', '5', '6', '7', '8', '9'])

In [48]:
# Write temp_dict to pickle file called modification_timestamp.pkl
with open('modification_timestamp.pkl', 'wb') as f:
    pickle.dump(temp_dict, f)

In [52]:
# delete user 6
del temp_dict['6']

In [54]:
timestamp_diff_dict = {}

for key, df_list in temp_dict.items():
    df_timestamp_diffs = []
    for df in df_list:
        # print key and column names with clear indication of which DataFrame we are looking at
        # this is useful for debugging


        print(key)
        print(df.columns)
        print("-----")
        first_timestamp = df['timestamp_modified'].iloc[0]
        last_timestamp = df['timestamp_modified'].iloc[-1]
        timestamp_difference = last_timestamp - first_timestamp
        # Convert to seconds
        timestamp_difference = timestamp_difference / 1000

        df_timestamp_diffs.append(timestamp_difference)
    
    timestamp_diff_dict[key] = df_timestamp_diffs

# Now, timestamp_diff_dict contains the timestamp difference for each DataFrame in the list for each key
print(timestamp_diff_dict)

1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
1
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
10
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
11
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
12
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
13
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
14
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
15
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
16
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
17
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
19
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
2
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
3
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
4
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
5
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
7
Index(['client_timestamp', 'x', 'y', 'button', 'state', 'window\n',
       'timestamp', 'timestamp_modified'],
      dtype='object')
-----
7

In [ ]:
result_dict = {}

# Iterate through the dictionary
for key, df_list in temp_dict.items():
    divided_dfs_list = []
    
    # Iterate through the list of dataframes
    for df in df_list:
        # Sort dataframe by 'timestamp_modified'
        df = df.sort_values(by='timestamp_modified')
        
        # Find the minimum and maximum timestamps
        min_timestamp = df['timestamp_modified'].min()
        max_timestamp = df['timestamp_modified'].max()
        
        # Divide the dataframe into 5-minute intervals (300,000 ms)
        interval_start = min_timestamp
        while interval_start <= max_timestamp:
            interval_end = interval_start + 300000
            
            # Filter rows within the 5-minute interval
            mask = (df['timestamp_modified'] >= interval_start) & (df['timestamp_modified'] < interval_end)
            divided_df = df[mask]
            
            if not divided_df.empty:
                divided_dfs_list.append(divided_df)
            
            interval_start = interval_end
            
    result_dict[key] = divided_dfs_list

In [64]:
# Check length of result_dict for each key
for key, df_lists in result_dict.items():
    for df_list in df_lists:
        print(key)
        print(len(df_list))
        print()

1
10000

1
10000

1
10000

1
10000

1
6628

1
9455

1
9828

1
9952

1
9461

1
6681

1
8439

1
4377

1
5176

1
4244

1
10000

1
8415

1
2655

1
2870

1
9174

1
6249

1
9889

1
10000

1
7654

1
756

1
1613

1
5459

1
1365

1
4307

1
6090

1
6571

1
9385

1
4508

1
8953

1
5774

1
4320

1
2661

1
306

1
2118

1
9484

1
9422

1
5871

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
9001

1
9617

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
8939

1
10000

1
10000

1
10000

1
8014

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
9187

1
10000

1
10000

1
10000

1
10000

1
452

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
9904

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
8936

1
9902

1
10000

1
10000

1
10000

1
10000

1
10000

1
5892

1
10000

1
10000

1
10000

1
10000

1
10000

1
8793

1
9209

1
2248

1
2381

1
2330

1
5624

1
7931

1
5260

1
10000

1
8735

1
6607

1
6972

1
4123

1
6731

1
10000

1
10000

1
9391

1
8575

1
9937

1
9617

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
6415

1
6068

1
10000

1
9358

1
8918

1
7885

1
10000

1
10000

1
10000

1
9875

1
10000

1
10000

1
9089

1
10000

1
10000

1
10000

1
10000

1
5321

1
9862

1
10000

1
7686

1
10000

1
9089

1
10000

1
10000

1
9733

1
10000

1
10000

1
10000

1
10000

1
9682

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
4861

1
9392

1
10000

1
7163

1
9948

1
4115

1
9899

1
10000

1
9201

1
7255

1
8378

1
9345

1
9206

1
8231

1
8093

1
9380

1
9169

1
9625

1
9611

1
10000

1
10000

1
10000

1
10000

1
7522

1
6677

1
430

1
485

1
9720

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
6349

1
4668

1
10000

1
10000

1
10000

1
10000

1
10000

1
10000

1
660

10
6789

10
7029

10
6402

10
7720

10
9630

10
8410

10
7551

10
2777

10
6987

10
8000

10
5347

10
7094

10
7443

10
7807

10
10000

10
9998

10
10000

10
10000

10
9897

10
9432

10
10000

10
10000

10
10000

10
9279

10
10000

10
10000

10
9544

10
5617

10
10000

10
10000

10
10000

10
10000

10
10000

10
10000

10
10000

10
10000

10
10000

10
10000

10
7497

10
9258

10
3850

10
2736

10
1406

10
4788

10
2741

10
7825

10
7309

10
8050

10
2568

10
2076

10
4013

10
1009

10
870

10
1336

10
767

10
102

10
1494

10
1642

10
1348

10
1163

10
1652

10
4245

10
2395

10
3365

10
1253

10
2754

10
2482

10
1172

10
133

10
4379

10
3758

10
1525

10
1486

10
3344

10
1036

10
4630

10
4944

10
2702

10
7313

10
3722

10
4091

10
1217

10
7957

10
6752

10
6919

10
8924

10
7768

10
7623

10
8601

10
7857

10
5921

10
9110

10
5599

10
4744

10
1384

10
2652

10
3385

10
2717

10
7254

10
5658

10
711

10
2611

10
2492

10
4336

10
4538

10
2263

10
3164

10
5426

10
5481

10
7890

10
8155

10
6070

10
6771

10
6428

10
4689

10
6829

10
7311

10
3384

10
7369

10
8974

10
6331

10
6139

10
3367

10
7471

10
6846

10
3479

10
2861

10
4481

10
9245

10
5265

10
4765

10
5368

10
6341

10
5399

10
4823

10
7412

10
9273

10
6258

10
8352

10
8971

10
9271

10
9247

10
6404

10
7491

10
9788

10
9644

10
7340

10
3897

10
8703

10
6526

10
7030

10
3503

10
7126

10
9183

10
9533

10
4618

10
2513

10
8572

10
9166

10
9250

10
8348

10
10000

10
9190

10
10000

10
9010

10
2174

10
3188

10
6719

10
6114

10
9151

10
4761

10
6958

10
9722

10
6219

10
1633

10
4780

10
2463

10
4233

10
1083

10
8513

10
5733

10
2686

10
5912

10
2564

10
4690

10
4440

10
4448

10
8194

10
4543

10
4500

10
7971

10
4864

10
4094

10
5034

10
4553

10
6042

10
7819

10
6492

10
1101

10
269

10
1447

10
632

10
2238

10
4450

10
4537

10
8

10
2244

10
6222

10
457

10
3326

10
1270

10
2104

10
2519

10
2370

10
3151

10
3475

10
1810

10
2111

10
3553

10
1906

10
420

10
3142

10
5268

10
6934

10
8995

10
275

10
426

10
2544

10
2855

10
1614

10
3084

10
2673

10
1558

10
4478

10
2174

10
1141

10
2042

10
3939

10
4701

10
2437

10
4967

10
3920

10
3842

10
2500

10
7904

10
5524

10
6691

10
3514

10
2472

10
3372

10
3347

10
5782

10
4726

10
7977

10
4110

10
6226

10
4877

10
3920

10
6201

10
7904

10
6323

10
5024

10
3063

10
5246

10
2664

10
602

10
6705

10
4642

10
2017

10
6501

10
3815

10
7978

10
2514

10
4014

10
4476

10
3832

10
3036

10
740

10
2518

10
1741

10
3474

10
7614

10
8945

10
7134

10
4618

10
2429

10
5463

10
6760

10
2892

10
4844

10
2725

10
3725

10
4610

10
2461

10
6749

10
5292

10
8613

10
6552

10
1514

10
6961

10
8511

10
5498

10
3498

10
4572

10
3720

10
2089

10
2903

10
5093

10
2586

10
5954

10
8925

10
6499

10
8573

10
4563

10
917

10
1354

10
2883

10
3723

10
6560

10
4188

10
5513

10
4783

10
2702

10
1342

10
2678

10
7740

10
7140

10
160

10
3688

10
10000

10
4426

10
1006

10
619

10
3117

10
7697

10
1193

10
658

10
1550

10
1542

10
3173

10
2242

10
9216

10
5474

10
619

10
5131

10
4674

10
5082

10
997

10
3329

10
1992

10
567

10
3472

10
3383

10
4434

10
10000

10
3816

10
3784

10
241

10
8000

10
8038

10
1374

10
1575

10
8533

10
7182

10
7373

10
5578

10
2812

10
4448

10
8107

10
6046

10
9710

10
8505

10
8059

10
1892

10
576

10
7246

10
6065

10
7887

10
2103

10
8021

10
4377

10
3710

10
6634

10
904

10
4065

10
8685

10
3831

10
882

10
428

10
3105

10
1716

10
5926

10
9203

10
6896

10
3380

10
4148

10
356

10
1368

10
2519

10
6220

10
1981

10
1774

10
991

10
492

10
4493

10
7672

10
2182

10
5740

10
2042

10
5400

10
6020

10
8171

10
4871

10
5399

10
2488

10
1046

10
4695

10
3253

10
3863

10
685

10
3479

10
2635

10
3729

10
1727

10
1721

10
2530

10
6139

10
6358

10
4308

10
4061

10
5462

10
2938

10
5517

10
4536

10
8647

10
5210

10
3790

10
5054

10
1403

10
2619

10
2499

10
10000

10
5720

10
380

10
5290

10
5099

10
4255

10
2470

10
8639

10
6597

10
1366

10
4751

10
3620

10
2226

10
7176

10
8356

10
5266

10
4769

10
745

10
2991

10
1511

10
2992

10
2700

10
5781

10
4631

10
6423

10
595

10
14

10
6686

10
1595

10
2959

10
59

10
1749

10
882

11
6311

11
9866

11
9940

11
9763

11
6040

11
1574

11
1647

11
57

11
3276

11
306

11
3849

11
2001

11
1470

11
201

11
4168

11
390

11
1895

11
5448

11
7241

11
4177

11
8862

11
9595

11
10000

11
10000

11
9815

11
9827

11
9696

11
9922

11
9969

11
9378

11
572

11
920

11
2066

11
1330

11
1157

11
1717

11
4061

11
2937

11
9823

11
9572

11
4701

11
7389

11
10000

11
10000

11
9925

11
9466

11
10000

11
9813

11
9324

11
9237

11
7267

11
1727

11
4544

11
6172

11
1094

11
6620

11
7727

11
9990

11
9697

11
10000

11
10000

11
10000

11
6063

11
7501

11
3975

11
4298

11
9606

11
5848

11
2492

11
4869

11
2130

11
2865

11
444

11
6704

11
9595

11
7782

11
8154

11
7980

11
3996

11
9997

11
8616

11
8184

11
8872

11
8950

11
8629

11
8929

11
9505

11
9858

11
9149

11
9054

11
10000

11
10000

11
9584

11
8372

11
10000

11
4408

11
5393

11
8832

11
9216

11
9290

11
8733

11
8050

11
8561

11
10000

11
10000

11
10000

11
9040

11
9699

11
9634

11
8193

11
6528

11
6294

11
6068

11
5025

11
6242

11
3053

11
4885

11
2314

11
2689

11
5173

11
3196

11
4154

11
1308

11
4484

11
4272

11
9123

11
8781

11
8861

11
4894

11
3831

11
9895

11
3648

11
3646

11
2331

11
4061

11
2647

11
1012

11
595

11
3005

11
8153

11
6981

11
2668

11
3138

11
6029

11
3411

11
2474

11
7280

11
5127

11
2258

11
6905

11
8966

11
9858

11
6030

11
4427

11
5939

11
7628

11
9213

11
7574

11
4463

11
7385

11
7543

11
6170

11
2519

11
4767

11
51

11
6223

11
7671

11
9969

11
7782

11
9892

11
8214

11
7939

11
9229

11
7962

11
5095

11
4699

11
1488

11
6470

11
9732

11
8221

11
6876

11
8111

11
8172

11
9978

11
8457

11
9972

11
9555

11
8195

11
8753

11
10000

11
10000

11
9960

11
9976

11
5931

11
9099

11
9345

11
9557

11
9479

11
9795

11
10000

11
9883

11
7630

11
7870

11
8014

11
9760

11
9081

11
8662

11
9974

11
9251

11
4998

11
5441

11
9314

11
9716

11
9851

11
9139

11
10000

11
9646

11
9527

11
9086

11
9731

11
8972

11
9939

11
9911

11
9985

11
9825

11
9979

11
10000

11
10000

11
10000

11
9841

11
9965

11
9785

11
9998

11
8889

11
9905

11
9139

11
9918

11
8754

11
9510

11
4688

11
7681

11
8919

11
9246

11
8658

11
9523

11
9500

11
9694

11
1643

11
3199

11
7650

11
10000

11
10000

11
9747

11
4982

11
7377

11
3378

11
9963

11
7783

11
5202

11
7297

11
9961

11
7170

11
9558

11
9861

11
9741

11
8055

11
8926

11
8640

11
5011

11
6750

11
8920

11
9807

11
7471

11
8655

11
9364

11
9968

11
10000

11
9155

11
9046

11
7003

11
9657

11
9406

11
7738

11
8304

11
4709

11
1201

11
2723

11
1474

11
4479

11
6885

11
999

11
900

11
2427

11
2612

11
6549

11
3631

11
6904

11
7705

11
2969

11
2646

11
5386

11
8754

11
8700

11
1923

11
4525

11
6683

11
5477

11
9592

11
9901

11
6069

11
8183

11
8196

11
7103

11
4365

11
3084

11
3794

11
3256

11
4395

11
7757

11
8738

11
8497

11
8030

11
4677

11
5106

11
6045

11
1730

11
4933

11
4479

11
3476

11
7103

11
6723

11
6840

11
111

11
4321

11
1752

11
3019

11
3650

11
2737

11
10000

11
4179

11
5920

11
7170

11
4807

11
8675

11
9700

11
1861

11
440

11
3636

11
1477

11
2260

11
3913

11
2756

11
3025

11
6174

11
4980

11
139

11
3503

11
6766

11
3246

11
885

11
4453

11
9511

11
494

11
8708

11
7301

11
8787

11
9185

11
6436

11
7669

11
4689

11
1919

11
3865

11
6220

11
7778

11
8833

11
8755

11
9296

11
7909

11
7606

11
9995

11
8140

11
10000

11
10000

11
8976

11
9937

11
5965

11
8626

11
9781

11
9868

11
10000

11
10000

11
9731

11
9311

11
8960

11
7526

11
8645

11
9607

11
9707

11
7376

11
10000

11
8417

11
8398

11
8470

11
3751

11
2498

11
7219

11
8676

11
5449

11
3895

11
7234

11
8416

11
8601

11
2026

11
7690

11
9170

11
10000

11
6671

11
6838

11
127

11
3819

11
7000

11
5658

11
1328

11
4000

11
1498

11
1275

11
788

11
6888

11
5748

11
1430

11
2219

11
1931

11
1175

11
518

11
83

11
971

11
2596

11
1182

11
5192

11
1

11
1033

11
4973

11
3548

11
6415

11
1938

11
6236

11
4610

11
2434

11
854

11
1855

11
1298

11
4357

11
4355

11
7233

11
7291

11
10000

11
9510

11
10000

11
9779

11
8436

11
10000

11
7603

11
9433

11
5104

11
5029

11
6280

11
4391

11
5242

11
6522

11
2179

11
4548

11
6742

11
6264

11
4018

11
3003

11
6071

11
10000

11
4603

11
5734

11
375

11
2889

11
4355

11
120

11
6694

11
9710

11
9398

11
9606

11
2463

11
7607

11
8814

11
7007

11
9581

11
8568

11
5161

11
8860

11
2915

11
6131

11
7723

11
9507

11
8531

11
6976

11
9278

11
8108

11
8427

11
7220

11
4113

11
6528

11
9698

11
8423

11
8952

11
9631

11
9452

11
8740

11
4440

11
6334

11
4403

11
5442

11
6956

11
7080

11
2013

11
1857

11
5515

11
6164

11
3146

11
3954

11
2685

11
4901

11
4257

11
6642

11
2187

11
2717

11
6193

11
7032

11
2452

11
6465

11
7453

11
8940

11
6730

11
2502

11
95

11
6859

11
4995

11
3959

11
1615

11
7570

11
5433

11
1112

11
3563

11
2371

11
5898

11
9258

11
9415

11
2646

11
726

11
2262

11
5443

11
7114

11
6065

11
4372

11
2607

11
3953

11
3824

11
7443

11
2391

11
3

11
5162

11
6808

11
2309

11
7290

11
6809

11
3180

11
818

11
1736

11
789

11
340

11
2913

11
4424

11
3415

11
5316

11
2886

11
4446

11
2645

11
8464

11
3894

11
810

12
149

12
3781

12
924

12
1646

12
8354

12
9062

12
2154

12
265

12
434

12
334

12
3810

12
2106

12
1615

12
1538

12
4287

12
1928

12
6075

12
2759

12
7255

12
7313

12
1634

12
9769

12
9500

12
2343

12
1974

12
1914

12
10000

12
10000

12
8864

12
1920

12
1209

12
1976

12
2969

12
7144

12
2652

12
9908

12
8182

12
9092

12
2333

12
3156

12
1252

12
3156

12
5995

12
5490

12
4176

12
2175

12
4440

12
7183

12
2758

12
2649

12
5180

12
4387

12
9673

12
7767

12
3264

12
6065

12
6370

12
5806

12
5751

12
4314

12
6554

12
3197

12
3325

12
3635

12
9159

12
10000

12
9688

12
10000

12
10000

12
10000

12
10000

12
9563

12
1870

12
2188

12
1740

12
2092

12
1346

12
3499

12
693

12
3530

12
4555

12
4384

12
1647

12
8490

12
9284

12
4377

12
8351

12
4687

12
5463

12
5081

12
1513

12
2969

12
2356

12
9359

12
7419

12
344

12
7966

12
2410

13
9419

13
8049

13
8650

13
9484

13
9169

13
9693

13
5730

13
6069

13
1899

13
2237

13
1686

13
1383

13
2798

13
4312

13
79

13
592

13
3475

13
9450

13
7313

13
8112

13
7072

13
9315

13
3088

13
3932

13
2531

13
1417

13
1801

13
1623

13
3249

13
4671

13
821

13
3089

13
6078

13
3383

13
1286

13
2390

13
937

13
5882

13
3830

13
1442

13
450

13
859

13
1257

13
5834

13
6765

13
5488

13
4100

13
6177

13
6571

13
4685

13
3892

13
4833

13
5782

13
5671

13
1071

13
137

13
1151

13
2201

13
764

13
1749

13
483

13
5997

13
2746

13
4986

13
4131

13
3971

13
8690

13
3846

13
7612

13
342

13
10000

13
7990

13
8765

13
4243

13
5153

13
5155

13
5574

13
6681

13
8685

13
961

13
2810

13
2939

13
1820

13
2600

13
1246

13
1139

13
6352

13
7011

13
4619

13
696

13
1169

13
2971

13
4288

13
8349

13
8597

13
8314

13
9104

13
8250

13
7074

13
4270

13
10000

13
9172

13
9522

13
8160

13
2851

13
4757

13
2142

13
2753

13
2371

13
3805

13
2834

13
1429

13
559

13
660

13
3967

13
364

13
1775

13
1569

13
7735

13
3077

13
4153

13
1879

13
1417

13
1631

13
2687

13
997

13
2685

13
4058

13
3587

13
4793

13
2053

13
4115

13
5302

13
4554

13
1674

13
628

13
2168

13
3261

13
4402

13
2537

13
6896

13
6326

13
6236

13
6452

13
1341

13
1182

13
2665

13
9166

13
3668

13
4309

13
1234

13
1532

13
2964

13
9173

13
907

13
6506

13
2121

13
9810

13
9832

13
8756

13
3608

13
915

13
4127

13
2760

13
1347

13
1268

13
1810

13
1730

13
719

13
1196

13
996

13
5317

13
2975

13
5455

13
3977

13
1111

13
528

13
388

13
3153

13
5914

13
1454

13
3022

13
8426

13
2734

13
2046

13
2442

13
561

13
1248

13
1848

13
1197

13
1157

13
4983

13
3498

13
873

13
1308

13
510

13
4699

13
4136

13
4760

13
4843

13
1610

13
46

13
7527

13
1587

13
129

13
7835

13
7430

13
4763

13
4830

13
1376

13
2719

13
6462

13
1021

13
2245

13
2180

13
3157

13
8955

13
4401

13
6990

13
7331

13
10000

13
7323

13
9757

13
8864

13
8104

13
9657

13
9837

13
9788

13
1899

13
3837

13
1986

13
6127

13
5706

13
8681

13
8294

13
1381

13
1676

13
4076

13
4674

13
1583

13
2798

13
4567

13
4953

13
3663

13
1405

13
5111

13
2599

13
4605

13
7250

13
6377

13
2411

13
7295

13
7354

13
8803

13
9250

13
4838

13
8304

13
6720

13
10000

13
8270

13
9686

13
9907

13
9715

13
10000

13
8299

13
7934

13
3091

13
397

13
6953

13
7046

13
8320

13
7892

13
3739

13
8559

13
4510

13
2529

13
4596

13
5342

13
4159

13
5678

13
9537

13
5422

13
8126

13
7205

13
8309

13
9840

13
6903

13
4093

13
8918

13
8293

13
6726

13
9003

13
9658

13
8078

13
6926

13
5708

13
1482

13
2783

13
1171

13
6385

13
5332

13
7031

13
4541

13
3448

13
7075

13
5812

13
9256

13
9793

13
8636

13
7899

13
7434

13
3217

13
3319

13
8118

13
9789

13
9451

13
10000

13
3228

13
7424

13
7979

13
7944

13
3942

13
5398

13
8250

13
4405

13
2923

13
4850

13
3450

13
8631

13
4902

13
7539

13
5830

13
5906

13
1636

13
2761

13
5456

13
4717

13
4813

13
3120

13
866

13
4433

13
7422

13
9803

13
8673

13
9951

13
1059

13
1721

13
161

13
1166

13
7797

13
8519

13
5699

13
6975

13
6777

13
3120

13
4179

13
6530

13
3778

13
772

13
7017

13
7555

13
4400

13
6713

13
8765

13
3378

13
6002

13
3503

13
7593

13
6062

13
2645

13
2076

13
1988

13
1978

13
1212

13
572

13
4919

13
4649

13
4108

13
5013

13
2276

13
1986

13
6885

13
3729

13
4428

13
8249

13
5922

13
2245

13
1350

13
4044

13
2591

13
152

13
286

13
3092

13
4357

13
4

13
1947

13
915

13
3440

13
8529

13
7777

13
3332

13
4104

13
3153

13
4561

13
292

13
6485

13
2516

13
3517

13
175

13
2929

13
1765

13
5708

13
5191

13
5197

13
4469

13
2771

13
10000

13
2450

13
2096

13
1633

13
2289

13
2872

13
7029

13
5989

13
823

13
1128

13
962

13
139

13
9969

13
1817

14
6534

14
3039

14
7919

14
4780

14
7006

14
7709

14
9520

14
9528

14
3106

14
5103

14
8912

14
6393

14
5748

14
9395

14
1158

14
822

14
3766

14
2319

14
4805

14
301

14
4

14
3277

14
2705

14
4227

14
820

14
630

14
3205

14
2425

14
5738

14
1053

14
6431

14
9529

14
4655

14
736

14
853

14
4207

14
3915

14
2036

14
3831

14
3809

14
6128

14
3227

14
672

14
6717

14
7015

14
4429

14
5935

14
7256

14
587

14
3202

14
2058

14
3298

14
1129

14
2080

14
4266

14
9549

14
5577

14
8205

14
8114

14
876

14
3625

14
8358

14
4400

14
787

14
5398

14
8818

14
4847

14
4163

14
6647

14
9033

14
2705

14
5434

14
4894

14
4292

14
3908

14
6242

14
4166

14
3736

14
2053

14
6750

14
6252

14
8558

14
7955

14
3949

14
7546

14
5320

14
1261

14
2052

14
8287

14
1885

14
4840

14
9418

14
9290

14
8035

14
8391

14
998

14
10000

14
6839

14
5399

14
4211

14
8606

14
4615

14
5813

14
9244

14
9425

14
9566

14
7960

14
7934

14
9659

14
9352

14
9707

14
6209

14
6481

14
7870

14
8755

14
4047

14
9300

14
7283

14
4405

14
2844

14
6344

14
2622

14
273

14
8685

14
4267

14
4500

14
1408

14
6359

14
754

14
1815

14
397

14
180

14
2607

14
913

14
4338

14
6190

14
2791

14
1182

14
5866

14
8121

14
8142

14
6176

14
2125

14
3287

14
2446

14
9710

14
7519

14
3897

14
3365

14
128

14
384

14
8268

14
4502

14
7295

14
4428

14
10000

14
10000

14
8912

14
9587

14
9550

14
10000

14
9592

14
8811

14
10000

14
10000

14
10000

14
9564

14
2598

14
931

14
6546

14
2081

14
7088

14
2341

14
9756

14
7385

14
9860

14
5695

14
9759

14
9562

14
4794

14
6039

14
8581

14
8514

14
4193

14
7205

14
2517

14
6333

14
701

14
9361

14
4660

14
4944

14
1565

14
1947

14
3851

14
7286

14
5178

14
8444

14
4041

14
3536

14
5959

14
5659

14
3937

14
4058

14
1653

14
7240

14
2144

14
2338

14
7433

14
1705

14
5851

14
8952

14
9931

14
9864

14
9390

14
8683

14
7266

14
8622

14
7422

14
4718

14
4081

14
742

14
5665

14
7972

14
711

14
3811

14
4992

14
9028

14
8202

14
3362

14
4066

14
3980

14
8372

14
6528

14
6831

14
5171

14
6833

14
1420

14
6782

14
3306

14
960

14
1597

14
3571

14
4961

14
5612

14
7236

14
2621

14
119

14
2171

14
5692

14
6948

14
8534

14
2847

14
6498

14
4028

14
7755

14
7029

14
8195

14
8347

14
8719

14
9926

14
8389

14
10000

14
10000

14
9079

14
10000

14
9072

14
6248

14
1638

14
780

14
2032

14
1457

14
594

14
297

14
4280

14
2948

14
6443

14
5300

14
3551

14
6478

14
6250

14
6720

14
9524

14
10000

14
10000

14
10000

14
10000

14
9452

14
973

14
5464

14
1911

14
1018

14
2945

14
3367

14
4105

14
1906

14
2558

14
3478

14
9464

14
10000

14
7127

14
2850

14
7926

14
5986

14
8698

14
9297

14
4250

14
2201

14
5975

14
6405

14
3593

14
8404

14
3631

14
4852

14
5460

14
3907

14
8112

14
4061

14
4473

14
6824

14
3244

14
1329

14
4179

14
4861

14
1638

14
3389

14
9739

14
5051

14
4

14
4759

14
5117

14
3302

14
4470

14
4642

14
5813

14
5063

14
4880

14
9622

14
9082

14
4217

14
4639

14
8023

14
4128

14
8625

14
6593

14
941

14
1410

14
2013

14
3965

14
7779

14
623

14
2201

14
3920

14
6468

14
944

14
5036

14
211

14
3383

14
6298

14
5911

14
1843

14
413

14
566

14
8221

14
7811

14
8728

14
3386

14
1097

14
5049

14
2196

14
173

14
4578

14
368

14
1506

14
2469

14
2

14
484

14
1

14
6612

14
5093

14
2286

14
3970

14
2630

14
6124

14
4281

14
10000

14
10000

14
9364

14
10000

14
10000

14
4699

14
8175

14
5067

14
10000

14
10000

14
9998

14
10000

14
10000

14
10000

14
10000

14
10000

14
10000

14
9627

14
10000

14
10000

14
9534

14
7623

14
528

14
413

14
3868

14
4416

15
372

15
1178

15
1352

15
3926

15
2422

15
1346

15
3025

15
5597

15
4115

15
1308

15
3546

15
3600

15
528

15
990

15

In [14]:
user_dict['1'][0]

          client_timestamp     x    y button state    window\n      timestamp
0           1570169899.971   694  489   None  Move  browsing\n  1570169899971
1            1570169899.99   703  473   None  Move  browsing\n  1570169899990
2       1570169900.0089998   713  454   None  Move  browsing\n  1570169900008
3           1570169900.028   725  436   None  Move  browsing\n  1570169900028
4           1570169900.046   737  417   None  Move  browsing\n  1570169900046
...                    ...   ...  ...    ...   ...         ...            ...
425866       1570232251.22  1785  822   None  Move  browsing\n  1570232251220
425867      1570232251.231  1789  820   None  Move  browsing\n  1570232251231
425868      1570232251.242  1790  819   None  Move  browsing\n  1570232251242
425869      1570232251.252  1791  818   None  Move  browsing\n  1570232251252
425870  1570232251.2670002  1792  818   None  Move  browsing\n  1570232251267

[270110 rows x 7 columns]

In [15]:
test_df = modify_timestamp(user_dict['1'][0])
test_df.head()

,client_timestamp,x,y,button,state,window\n,timestamp,timestamp_modified
0,1570169899.971,694,489,None,Move,browsing\n,1570169899971,1570169899971
1,1570169899.99,703,473,None,Move,browsing\n,1570169899990,1570169899981
2,1570169900.0089998,713,454,None,Move,browsing\n,1570169900008,1570169899991
3,1570169900.028,725,436,None,Move,browsing\n,1570169900028,1570169900001
4,1570169900.046,737,417,None,Move,browsing\n,1570169900046,1570169900011

In [17]:
# Iterate through the keys and apply the modify_timestamp function
for key in user_dict:
    user_dict[key] = [modify_timestamp(df) for df in user_dict[key]]

IndexError: single positional indexer is out-of-bounds

In [5]:
new_dict = user_dict#{key: user_dict[key] for key in ['1', '2']}

print(new_dict)

NameError: name 'user_dict' is not defined